// svelte-app/src/products/ProductList.svelte
<script>
  import { CardContent } from '../components';

  export let products = [];
</script>

<div>
  {#if !products.length}
    <div>Loading data ...</div>
  {/if}
  <ul class="list">
    {#each products as { id, name, description } (id)}
      <li role="presentation">
        <div class="card">
          <CardContent {name} {description} />
        </div>
      </li>
    {/each}
  </ul>
</div>

// react-app/src/products/ProductList.js
import React from 'react';

import { CardContent } from '../components';

function ProductList({ products }) {
  return (
    <div>
      {products.length === 0 && <div>Loading data ...</div>}
      <ul className="list">
        {products.map((product) => (
          <li key={product.id} role="presentation">
            <div className="card">
              <CardContent
                name={product.name}
                description={product.description}
              />
            </div>
          </li>
        ))}
      </ul>
    </div>
  );
}

export default ProductList;
