// vue-app/src/views/products/product-list.vue
<script>
import CardContent from '@/components/card-content.vue';

export default {
  name: 'ProductList',
  props: {
    products: {
      type: Array,
      default: () => [],
    },
  },
  components: { CardContent },
};
</script>

<template>
  <div>
    <div v-if="!products.length">Loading data ...</div>
    <ul class="list">
      <li v-for="product in products" :key="product.id" role="presentation">
        <div class="card">
          <CardContent
            :name="product.name"
            :description="product.description"
          />
        </div>
      </li>
    </ul>
  </div>
</template>

// angular-app/src/app/products/product-list.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { Product } from '../core';

@Component({
  selector: 'app-product-list',
  template: `
    <div *ngIf="!products?.length">Loading data ...</div>
    <ul class="list">
      <li
        role="presentation"
        *ngFor="let product of products; trackBy: trackByProduct; let i = index"
      >
        <div class="card">
          <app-card-content
            [name]="product.name"
            [description]="product.description"
          ></app-card-content>
        </div>
      </li>
    </ul>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  standalone: false,
})
export class ProductListComponent {
  @Input() products: Product[];

  trackByProduct(index: number, product: Product): number {
    return product.id;
  }
}
